/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RAIZ_H_RPCGEN
#define _RAIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct datos {
	float a;
	float b;
	float c;
};
typedef struct datos datos;

struct raiz {
	float r1;
	float r2;
	int error;
};
typedef struct raiz raiz;

struct complex {
	float real;
	float imag;
};
typedef struct complex complex;

#define RAIZ_PROG 2
#define RAIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RESUELVE 1
extern  struct raiz * resuelve_1(datos *, CLIENT *);
extern  struct raiz * resuelve_1_svc(datos *, struct svc_req *);
#define COMPLEJO 2
extern  struct complex * complejo_1(datos *, CLIENT *);
extern  struct complex * complejo_1_svc(datos *, struct svc_req *);
extern int raiz_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RESUELVE 1
extern  struct raiz * resuelve_1();
extern  struct raiz * resuelve_1_svc();
#define COMPLEJO 2
extern  struct complex * complejo_1();
extern  struct complex * complejo_1_svc();
extern int raiz_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos (XDR *, datos*);
extern  bool_t xdr_raiz (XDR *, raiz*);
extern  bool_t xdr_complex (XDR *, complex*);

#else /* K&R C */
extern bool_t xdr_datos ();
extern bool_t xdr_raiz ();
extern bool_t xdr_complex ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RAIZ_H_RPCGEN */
