/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "raiz.h"

bool_t
xdr_datos (XDR *xdrs, datos *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->c))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_raiz (XDR *xdrs, raiz *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->r1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->r2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_complex (XDR *xdrs, complex *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->real))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->imag))
		 return FALSE;
	return TRUE;
}
